sudo: false
language: node_js
node_js:
- node
- '6'
- '5'
- '4'
deploy:
  provider: heroku
  api_key:
    secure: YTDOPc2ypEZii+R++YwJxabHOwSWsdfL7Ux3b/S9BX8kAfi8zU5W27u6lpqa1BQJ6KzZX4FY/ANBGrU/93LCIg4edwg2juHY4Bqt/wqfhqgf/vWMTD//wy5ItEo5u2nebF5wj4PqBZqmP4EUI9bNj2YqYeWnpn4U+QtaZajlGCU+uFQD4G+nJybiRCAMmFIbOY6KEAHsZOH5QtXz3DXuZmLOw8wTuN2bTfNihlLXzRdBig6YRj9BTAnSK5OwWluPepW7fFS1FU0vxfTtPDHlVPVZZDq0gGpxcY86HTuCA6SnzpAyc0pE4ErTzBFJFLXvQGDxv0xOxUH1mAg7sZlszsib6fJiTpNEMDY4AOeGVMLZBxV5t3bOmQc9jRHfPQn3s/1MhGvlvPWfci2e8T8gJfs4UUgtkgtSzB3DXks9BalRedETtqLnXvzNgJr1GiG2Gma1CJad5EGvAc9k4rsEVdI5DpkRBY88K+m47A2xktySGQP4nj4zI7IyO7davXp/cvDngryMEM8KuPgf/yaGuX5v9RVhDlc9DhcnGtYgrJ6Ke/H06CPqLSlTlNBfmuoeiUMromNbyCEr6nkE7Ps2fUzKMJPFrCY8v7Ke9zkOdLXuhveb8xILSQ8G2HQ1Mf9DgUUnPnWpjWSuxYgPsx1Qqp5Cy2/QE9yk+3OEIlRDzrQ=
  app: restaurants-app-mongoose-
  on:
    repo: danieldowler/restaurants-app-mongoose-